### ISSUE TITLE
Implement ServerConfig database entity

### ISSUE THREAD

**Issue by RheaAyase** [RheaAyase/Botwinder.core#41]
Use other database entities as an example to finish the implementation of the [ServerConfig.cs](https://github.com/RheaAyase/Botwinder.core/blob/master/Entities/ServerConfig.cs)

Reference the database design image in #6 

Use `TypeName = "varchar(255)"` for `string` type in the DB,
`TypeName = "text"` for the `text` type,
and `TypeName = "tinyint"` for enums (they're integer in the db).
Use `guid` instead of integer for any `discord id` values (channelid, serverid, userid, roleid)
and `Int64` for all the other `integer` types in the DB.

**Comment by MasterChief-John-117** [comment]
Working on this now.

**Comment by MasterChief-John-117** [comment]
Github is pain (if someone else wants to hop on this I won't mind)

**Comment by DokaDoka** [comment]
I think I know what to do, I'll take a crack at it
