### ISSUE TITLE
Implement UserData database entity

### ISSUE THREAD

**Issue by RheaAyase** [RheaAyase/Botwinder.core#42]
Use other database entities as an example to finish the implementation of the [UserData.cs](https://github.com/RheaAyase/Botwinder.core/blob/master/Entities/UserData.cs)

Reference the database design image in #6 (table `users`)

Use `TypeName = "varchar(255)"` for `string` type in the DB,
`TypeName = "text"` for the `text` type,
and `TypeName = "tinyint"` for enums (they're integer in the db).
Use `guid` instead of integer for any `discord id` values (channelid, serverid, userid, roleid)
and `Int64` for all the other `integer` types in the DB.

**Comment by DokaDoka** [comment]
Well, I made a commit but when I got to make a pull request it seems to want to apply the changes I made to ServerConfig.cs as well, again, I'm gonna... not touch anything, maybe I should have forked again

**Comment by RheaAyase** [comment]
You **have to** create a new branch for everything, never do anything in the same branch twice. It's possible but it's also a lot of problems.
